---
title: "Country Economic Memorandum 2.0"
output: 
  flexdashboard::flex_dashboard:
    social: menu
runtime: shiny
---


```{r global, include=FALSE}
# Loading packages
library(leaflet)
library(rgdal)
library(raster)
library(dplyr)
library(formattable)

```




Growth Decomposition 
======================================
```{r include=FALSE}
# Read the World Bank official shapefile
WB_map <- readOGR("WBG_Poly/WB_CountryPolys.shp")
CJK <- c("CHN","JPN","KOR")
# Read additional data and merge it to the shape file 
df <- data.frame(
  ISO_Codes = WB_map@data$ISO_Codes,
  val = ifelse(WB_map@data$ISO_Codes %in% CJK,1,0),
  label = ifelse(WB_map@data$ISO_Codes %in% CJK,"Available","Unavailable")
)

WB_map@data <- data.frame(WB_map@data, df[match(WB_map@data[,"ISO_Codes"], df[,"ISO_Codes"]),])
pal2 <- colorNumeric(c("grey","#009FDA"), domain = WB_map@data$val)

```

Column {data-width=618}
------------------------------------------------------------------------------------------
### Data Availability around the World
```{r}
WB_map %>% 
  leaflet() %>% 
  addPolygons(weight = 1, 
              # add labels that display mean income
              color = "grey",
              fillColor = ~pal2(val),
              fillOpacity = 1,
              opacity=1,
              label = ~paste0(Names," - ",label),
              # highlight polygons on hover
              highlightOptions = highlightOptions(weight = 2, color = "white",
                                                  bringToFront = TRUE)) 
```

Column {data-width=382}
------------------------------------------------------------------------------------------
### Table 
```{r}
df <- data.frame(
  name = c("Bob", "Ashley", "James", "David", "Jenny", 
           "Hans", "Leo", "John", "Emily", "Lee"), 
  age = c(28, 27, 30, 28, 29, 29, 27, 27, 31, 30),
  grade = c("C", "A", "A", "C", "B", "B", "B", "A", "C", "C"),
  test1_score = c(8.9, 9.5, 9.6, 8.9, 9.1, 9.3, 9.3, 9.9, 8.5, 8.6),
  test2_score = c(9.1, 9.1, 9.2, 9.1, 8.9, 8.5, 9.2, 9.3, 9.1, 8.8),
  registered = c(TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
  stringsAsFactors = FALSE)

formattable(df, list(
  age = color_tile("white", "orange"),
  grade = formatter("span", style = x ~ ifelse(x == "A", 
                                               style(color = "green", font.weight = "bold"), NA)),
  area(col = c(test1_score, test2_score)) ~ normalize_bar("#009FDA", 0.2),
  registered = formatter("span",
                         style = x ~ style(color = ifelse(x, "green", "red")),
                         x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))
))
```

### Table 